export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";

export const ALL_PRODUCTDETAIL_SUCCESS="ALL_PRODUCT_SUCCESS_DETAIL";
export const ALL_PRODUCTDETAIL_FAIL="ALL_PRODUCT_FAIL_DETAIL";
export const ALL_PRODUCTDETAIL_REQUEST="ALL_PRODUCT_REQUEST_DETAIL";

export const ALL_CLEAR_ERROR="ALL_CLEAR_ERROR";
